# The URL the site will be built for
base_url = "https://www.geoaxis.cz"
default_language = "cs"
title = "Geoaxis"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

minify_html = false
generate_robots_txt = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[languages.cs.translations]
toggle_nav = "Přepnout navigaci"
home = "Úvodní stránka"
contact = "Kontakt"
address = "Adresa"

[languages.en]
title = "Geoaxis"

[languages.en.translations]
toggle_nav = "Toggle navigation"
home = "Home"
contact = "Contact"
address = "Address"

[extra]
# Put all your custom variables here
